# Generated by Django 3.1.2 on 2020-12-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infomation_1', models.TextField()),
                ('infomation_2', models.TextField()),
                ('infomation_3', models.TextField()),
            ],
        ),
    ]
