# Generated by Django 3.1.2 on 2020-12-14 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0007_completion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Completion',
        ),
    ]
