# Generated by Django 3.1.2 on 2020-12-14 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0008_delete_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prequestionnaireanswer',
            name='spammer_check',
        ),
    ]
