# Generated by Django 3.1.2 on 2020-12-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0009_remove_prequestionnaireanswer_spammer_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='is_public_institute',
            field=models.IntegerField(default=0),
        ),
    ]
