# Generated by Django 3.1.2 on 2020-12-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0011_auto_20201214_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskanswer',
            name='video_content',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
