# Generated by Django 3.1.2 on 2020-12-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstudy', '0012_taskanswer_video_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskanswer',
            name='reason',
            field=models.TextField(),
        ),
    ]
