# Generated by Django 3.1.2 on 2020-12-14 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userstudy', '0013_auto_20201214_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskanswer',
            name='video_content',
        ),
        migrations.CreateModel(
            name='VideoContentCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_content', models.TextField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
